### Spring properties
# Service registers under this name
spring:
  application:
    name: customer-microservice

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://192.168.99.100:8181/eureka/
    instance:
       prefer-ip-address: true
       leaseRenewalIntervalInSeconds: 1
       leaseExpirationDurationInSeconds: 2

# HTTP Server (Tomcat) Port
server: 
  port: 4444

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false